- name: QUERY Networks on VBGW Switches
  dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/v2/fabrics/AUTOMATION-LAB-DC{{dc_num}}/networks/{{network}}/status"
  register: results
- name: QUERY Result
  set_fact:
    data: "{{ results.response.DATA }}"
- name: Display Result
  ansible.builtin.debug:
    msg: "{{ data }}"
- name: Set Details
  set_fact:
    networkTemplateConfig: "{{data.networkTemplateConfig}}"
- name: Display Template Config
  ansible.builtin.debug:
    msg: "{{ networkTemplateConfig }}"
- name: Set enableL3OnBorder
  vars:
    updatedValues:
      enableL3OnBorder: true
  set_fact:
    newConfig: "{{ networkTemplateConfig | combine(updatedValues, recursive=true) }}"
- name: Updated Template Config
  ansible.builtin.debug:
    msg: "{{ newConfig }}"
- name: Build Link JSON Payload from Template
  set_fact:
    payload: "{{ lookup('ansible.builtin.template', './network_json.j2') }}"
- name: JSON Payload
  ansible.builtin.debug:
    msg: "{{ payload }}"
- name: PUT Network Template JSON
  dcnm_rest:
    method: PUT
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/AUTOMATION-LAB-DC{{dc_num}}/networks/{{network}}"
    data: "{{ payload | to_json }}"
  ignore_errors: true
