- name: Build JSON Payload
  set_fact:
    payload:
      destFabric: "AUTO-POD{{pod_num}}-MSD"
      sourceFabric: "AUTO-POD{{pod_num}}-DC{{dc_num}}"
- name: JSON Payload
  ansible.builtin.debug:
    msg: "{{ payload }}"
- name: POST MSD Add Fabric JSON
  dcnm_rest:
    method: POST
    path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/msdAdd
    data: "{{ payload | to_json }}"
  ignore_errors: true
