- name: POST Recalculate Fabric (Config Save)
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-DC{{dc_num}}/config-save"
    data: null
  # timeout: 180
- name: Pause for 1 minute
  ansible.builtin.pause:
    minutes: 1
- name: POST Deploy Fabric (Config Deploy)
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-DC{{dc_num}}/config-deploy"
    data: null
  ignore_errors: yes
  # timeout: 180
