all:
  vars:
    ansible_user: "admin"
    ansible_password: "C1sco12345"
    ansible_connection: ansible.netcommon.httpapi
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
  children:
    ndfc:
      hosts:
        198.19.133.100:
            ansible_network_os: cisco.dcnm.dcnm
